name: Deploy Maven Modules

on:
  create:
    branches:
      - 'release-*'  # Match any branch that starts with "release-"
    paths:
      - '**.java'
      - '**/pom.xml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          server-id: github

      - name: Build & Deploy with Maven
        run: mvn -B deploy -DskipTests -Drevision=0.0.1-SNAPSHOT -f ./parent/pom.xml -s ./settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token automatically handled by GitHub Actions
